version: '3'
services:
  db:
    image: digitalpatterns/timescaledb:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/config/setup-keycloakdb.sh:/docker-entrypoint-initdb.d/004-setup-keycloakdb.sh

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    restart: on-failure
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloakPwd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/realm-export.json
    ports:
      - 8080:8080
    depends_on:
      - db

  flyway:
    image: quay.io/ukhomeofficedigital/csv_loader:latest
    container_name: flyway
    entrypoint: /bin/bash -c /flyway/run.sh
    environment:
      - DB_HOSTNAME=db
      - DB_NAME=ref
    depends_on:
      - db

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    restart: on-failure
    environment:
      - POSTGREST_NAME=postgrest
      - PGRST_DB_ANON_ROLE=anonuser
      - PGRST_DB_SCHEMA=public
      - PGRST_JWT_AUD=postgrest
      - PGRST_ROLE_CLAIM_KEY=.postgrest
      - PGRST_DB_URI=postgres://authuser:authPwd@db:5432/ref
      - PGRST_SERVER_PROXY_URI=http://127.0.0.1:3000/
      - PGRST_DB_POOL=30
      - PGRST_DB_POOL_TIMEOUT=20
    ports:
      - 3000:3000
    depends_on:
      - db
      - flyway

  validate:
    image: quay.io/ukhomeofficedigital/csv_loader:latest
    container_name: validate
    command: "/validation/validate.py"
    depends_on:
      - db
      - flyway

  csv_loader:
    image: quay.io/ukhomeofficedigital/csv_loader:latest
    container_name: csv_loader
    command: "/csvs/load_csvs.py -e docker"
    depends_on:
      - db
      - flyway
      - validate
      - postgrest
