services:
  flyway:
#    build: .
    volumes:
      - ./flyway:/flyway

  validate:
#    build: .
    volumes:
      - ./validation:/validation
      - ./flyway:/flyway

  csv_loader:
#    build: .
    volumes:
      - ./csvs:/csvs

  postgrest:
    environment:
      - PGRST_JWT_SECRET={"kid":"Kknk650ZQe6Gre8Ff_PcckGUBrQS-Hr_dhn2H-yWPwI","kty":"RSA","alg":"RS256","n":"nDHzAx53gv6a1X1P4PDhChheVLujZ6QtfjmGo6GfgV7XC6MSwPiCWyNcA_oMXnhBbINCxq41xxXu83SANPYoB11KEphkl4AIwmwWpUH36HYHpRm3sDljyUPWDt0-FKceaOSR8sBx_TGCD3If5v1gyEa4NLxKHLVkcv3JOQloGCXPr3rLrMFIcDJg4HvwJNiIPFFfP1mQccbhbvGBahZLOUxb5fbjU0MmOcSYZoVqx6lD7E8VQO0I__u84leRh5GSZmi24B4vhmEzC6_4WJE6ftapdMOR8nl_qgl5RTM9DCkeS8gf9MyymgVV-YI-QjEGd8vb7SUtGR92796i6g4xgw","e":"AQAB"}
